version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  price_publisher:
    build: .
    command: sh -c "uvicorn price_publisher:app --host 0.0.0.0 --reload"
    volumes:
      - ./code:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  price_scraper:
    build: .
    volumes:
      - ./code:/app
    working_dir: /app
    ports:
      - "8001:8001"
    depends_on:
      - redis

  price_subscriber:
    build: .
    command: sh -c  "streamlit run price_subscriber.py"
    volumes:
      - ./code:/app
    working_dir: /app
    ports:
      - "8501:8501"
    depends_on:
      - redis